# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stable_diffusion_node.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bstable_diffusion_node.proto\x12\x10space_bodffusion\"\x10\n\x0eGetTaskRequest\"\x14\n\x12PostResultResponse\"\xf4\x01\n\x16StableDiffusionRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\x12\r\n\x05width\x18\x02 \x01(\r\x12\x0e\n\x06height\x18\x03 \x01(\r\x12\x1b\n\x13num_inference_steps\x18\x04 \x01(\r\x12\x16\n\x0eguidance_scale\x18\x05 \x01(\x02\x12\x1c\n\x0fnegative_prompt\x18\x06 \x01(\tH\x00\x88\x01\x01\x12\x1d\n\x15num_images_per_prompt\x18\x07 \x01(\r\x12\x12\n\nrequest_id\x18\x08 \x01(\x0c\x12\x11\n\trequester\x18\t \x01(\tB\x12\n\x10_negative_prompt\"\x89\x01\n\x17StableDiffusionResponse\x12\x12\n\nrequest_id\x18\x01 \x01(\x0c\x12\x0e\n\x06images\x18\x02 \x03(\x0c\x12\x0e\n\x06prompt\x18\x03 \x01(\t\x12\x0c\n\x04\x63ost\x18\x04 \x01(\x02\x12\x1a\n\rout_of_memory\x18\x05 \x01(\x08H\x00\x88\x01\x01\x42\x10\n\x0e_out_of_memory2\xcf\x01\n\x13StableDiffusionNode\x12W\n\x07GetTask\x12 .space_bodffusion.GetTaskRequest\x1a(.space_bodffusion.StableDiffusionRequest\"\x00\x12_\n\nPostResult\x12).space_bodffusion.StableDiffusionResponse\x1a$.space_bodffusion.PostResultResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stable_diffusion_node_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GETTASKREQUEST._serialized_start=49
  _GETTASKREQUEST._serialized_end=65
  _POSTRESULTRESPONSE._serialized_start=67
  _POSTRESULTRESPONSE._serialized_end=87
  _STABLEDIFFUSIONREQUEST._serialized_start=90
  _STABLEDIFFUSIONREQUEST._serialized_end=334
  _STABLEDIFFUSIONRESPONSE._serialized_start=337
  _STABLEDIFFUSIONRESPONSE._serialized_end=474
  _STABLEDIFFUSIONNODE._serialized_start=477
  _STABLEDIFFUSIONNODE._serialized_end=684
# @@protoc_insertion_point(module_scope)
