# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import stable_diffusion_node_pb2 as stable__diffusion__node__pb2


class StableDiffusionNodeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetTask = channel.unary_unary(
                '/space_bodffusion.StableDiffusionNode/GetTask',
                request_serializer=stable__diffusion__node__pb2.GetTaskRequest.SerializeToString,
                response_deserializer=stable__diffusion__node__pb2.StableDiffusionRequest.FromString,
                )
        self.PostResult = channel.unary_unary(
                '/space_bodffusion.StableDiffusionNode/PostResult',
                request_serializer=stable__diffusion__node__pb2.StableDiffusionResponse.SerializeToString,
                response_deserializer=stable__diffusion__node__pb2.PostResultResponse.FromString,
                )
        self.UpdateProgress = channel.stream_unary(
                '/space_bodffusion.StableDiffusionNode/UpdateProgress',
                request_serializer=stable__diffusion__node__pb2.UpdateProgressMessage.SerializeToString,
                response_deserializer=stable__diffusion__node__pb2.UpdateProgressResponse.FromString,
                )


class StableDiffusionNodeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetTask(self, request, context):
        """client connects to server and receives requests from server for processing
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PostResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateProgress(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StableDiffusionNodeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetTask': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTask,
                    request_deserializer=stable__diffusion__node__pb2.GetTaskRequest.FromString,
                    response_serializer=stable__diffusion__node__pb2.StableDiffusionRequest.SerializeToString,
            ),
            'PostResult': grpc.unary_unary_rpc_method_handler(
                    servicer.PostResult,
                    request_deserializer=stable__diffusion__node__pb2.StableDiffusionResponse.FromString,
                    response_serializer=stable__diffusion__node__pb2.PostResultResponse.SerializeToString,
            ),
            'UpdateProgress': grpc.stream_unary_rpc_method_handler(
                    servicer.UpdateProgress,
                    request_deserializer=stable__diffusion__node__pb2.UpdateProgressMessage.FromString,
                    response_serializer=stable__diffusion__node__pb2.UpdateProgressResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'space_bodffusion.StableDiffusionNode', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class StableDiffusionNode(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/space_bodffusion.StableDiffusionNode/GetTask',
            stable__diffusion__node__pb2.GetTaskRequest.SerializeToString,
            stable__diffusion__node__pb2.StableDiffusionRequest.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PostResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/space_bodffusion.StableDiffusionNode/PostResult',
            stable__diffusion__node__pb2.StableDiffusionResponse.SerializeToString,
            stable__diffusion__node__pb2.PostResultResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateProgress(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/space_bodffusion.StableDiffusionNode/UpdateProgress',
            stable__diffusion__node__pb2.UpdateProgressMessage.SerializeToString,
            stable__diffusion__node__pb2.UpdateProgressResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
